version: "3.6"
services:
  web:
    build: .
    depends_on:
      - db
    environment:
      SECRET_KEY_BASE: yDqPBrnjgmD2M3ByI9rHmkrP169y0w2rHfMIR0Qv5M/uy4SL78isYAYyyYv2RJ9r
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: plan_picker_prod
      PGPORT: 5432
      PGHOST: db
    ports:
      - "4000:4000"
    volumes:
      - .:/app
  db:
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    image: "postgres:13-alpine"
    restart: always
    ports:
      - "5444:5432"
    volumes:
      - "pgdata:/var/lib/postgresql/data"
volumes:
  pgdata:
